// @generated by tools/gen_registry.mjs — DO NOT EDIT BY HAND.
// Regenerate after adding/removing a learning song: node tools/gen_registry.mjs
import type { LearningTiming } from "../types";
import t_01_aiueo from "../../timing/01-aiueo.learning.json";

export const GENERATED_LEARNING_SONGS: { id: string; timing: LearningTiming }[] = [
  { id: "01-aiueo", timing: t_01_aiueo as unknown as LearningTiming },
];
