#!/usr/bin/env node
// gen_registry.mjs — generate the learning-song registry from the timing folder.
//
//   node tools/gen_registry.mjs
//
// Scans video/timing/*.learning.json and writes
// video/src/songs/learning-registry.generated.ts with one static import + one
// array entry per PUBLIC song (a song whose source folder exists under learning/).
// Adding a song no longer means hand-editing a .tsx — build its timing and rerun.
//
// PRIVACY SEAM: only songs with a learning/<id>/ folder are written into the
// committed generated file. Personal learning songs (gitignored timing) are left
// out so a clean checkout / CI never references a private file.

import { readdirSync, existsSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const TIMING = resolve(REPO, "video/timing");
const OUT = resolve(REPO, "video/src/songs/learning-registry.generated.ts");

const SUFFIX = ".learning.json";
const ident = (id) => "t_" + id.replace(/[^a-zA-Z0-9]/g, "_"); // valid JS import name

const ids = readdirSync(TIMING)
  .filter((f) => f.endsWith(SUFFIX))
  .map((f) => f.slice(0, -SUFFIX.length))
  .filter((id) => existsSync(resolve(REPO, "learning", id))) // public strand only
  .sort();

const imports = ids
  .map((id) => `import ${ident(id)} from "../../timing/${id}${SUFFIX}";`)
  .join("\n");

const entries = ids
  .map((id) => `  { id: ${JSON.stringify(id)}, timing: ${ident(id)} as unknown as LearningTiming },`)
  .join("\n");

const body = `// @generated by tools/gen_registry.mjs — DO NOT EDIT BY HAND.
// Regenerate after adding/removing a learning song: node tools/gen_registry.mjs
import type { LearningTiming } from "../types";
${imports}

export const GENERATED_LEARNING_SONGS: { id: string; timing: LearningTiming }[] = [
${entries}
];
`;

writeFileSync(OUT, body);
console.log(`wrote ${ids.length} song(s) -> video/src/songs/learning-registry.generated.ts`);
console.log(`  ${ids.join(", ") || "(none)"}`);
